= Generate AI templated files

image::c-key.svg["Computate c key"]

== Using AI to generate more code

When you are building a custom data-driven website, not all code files are easy to generate or fit a standard template. 
The Computate Smart Website Builder automatically indexes all of your source code into a search engine to: 

- Keep track of all of your Java project dependencies. 
- Keep track of all of your Java imports. 
- Store information about all Java models in your project. 

Java models can have very different characteristics: 

- Some data models store data only in the search engine. 
- Some data models store data in the database. 
- Some data models require fine-grained authorization to data. 
- Some data models are public data. 
- Some data models have a REST API. 
- Some data models have search pages, display pages, or user pages. 
- Some data models have public downloads, some have authorized downloads. 
- Some data models have custom APIs that don't fit a typical design. 

All of these characteristics can be learned by a machine by parsing your code, and indexing the data in a search engine. 
We can allow the machine to write our code for us as we code. 
Then we just need to compile and run our application and see the results. 

=== Run the Computate AI code watcher service

Enable code generation in your OpenShift AI Workbench by following the `+01-run-computate-ai-code-watcher.ipynb+` Jupyter Notebook in the files of VSCode and running each command in the Jupyter Notebook with the Bash Kernel.

=== Generate AI template files

Begin the template files that require some artificial intelligence to be written by following the `+02-generate-ai-template-files.ipynb+` Jupyter Notebook in the files of VSCode and running each command in the Jupyter Notebook with the Bash Kernel.

== Next

Next, you will automatically generate the Open API specification, database schema, and initial database tables for your new data-driven platform. 
